apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: root-location
spec:
  type: github
  targets:
    - https://raw.githubusercontent.com/spaschoalick/backstage/main/databases/catalog-info.yaml
