apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: daki-postgres-database
  title: Daki PostgreSQL Database
  description: Cria um database PostgreSQL usando Crossplane
  tags:
    - crossplane
    - postgresql
    - database
    - daki
spec:
  owner: platform-team
  type: resource

  parameters:
    - title: Informações do Database
      required:
        - databaseName
        - claimName
      properties:
        databaseName:
          title: Nome do Database
          type: string
          description: Nome do database PostgreSQL (use snake_case, ex. myapp_production)
          pattern: '^[a-z][a-z0-9_]*$'
          ui:autofocus: true
          ui:help: 'Use snake_case. Ex: myapp_production, app_staging'
        
        claimName:
          title: Nome do Claim
          type: string
          description: Nome do recurso Kubernetes (use kebab-case, ex. myapp-production)
          pattern: '^[a-z][a-z0-9-]*$'
          ui:help: 'Use kebab-case. Ex: myapp-production, app-staging'

    - title: Configurações Avançadas
      properties:
        connectionLimit:
          title: Limite de Conexões
          type: integer
          description: Máximo de conexões simultâneas (-1 = ilimitado)
          default: -1
          ui:help: 'Use -1 para ilimitado ou um número positivo para limitar'
        
        allowConnections:
          title: Permitir Conexões
          type: boolean
          description: Permite conexões ao database
          default: true
          ui:help: 'Desabilite para manutenção'
        
        deletionPolicy:
          title: Política de Deleção
          type: string
          description: O que acontece ao deletar o claim
          default: Delete
          enum:
            - Delete
            - Orphan
          enumNames:
            - 'Delete - Remove database do PostgreSQL'
            - 'Orphan - Mantém database no PostgreSQL (seguro)'
          ui:help: 'Orphan é recomendado para produção'
        
        environment:
          title: Ambiente
          type: string
          description: Ambiente do database
          default: development
          enum:
            - development
            - staging
            - production
          enumNames:
            - 'Development'
            - 'Staging'
            - 'Production'
        
        providerConfigRef:
          title: Provider Config
          type: string
          description: Nome do ProviderConfig do Crossplane
          default: poc-postgres-aurora
          ui:help: 'Deixe o padrão se não souber'

  steps:
    - id: fetch-base
      name: Preparar template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          databaseName: ${{ parameters.databaseName }}
          claimName: ${{ parameters.claimName }}
          connectionLimit: ${{ parameters.connectionLimit }}
          allowConnections: ${{ parameters.allowConnections }}
          deletionPolicy: ${{ parameters.deletionPolicy }}
          environment: ${{ parameters.environment }}
          providerConfigRef: ${{ parameters.providerConfigRef }}

    - id: log
      name: Log dos arquivos gerados
      action: debug:log
      input:
        message: 'Arquivos gerados para ${{ parameters.claimName }}'

  output:
    links:
      - title: Arquivo YAML gerado
        icon: description
        url: ${{ steps['fetch-base'].output.targetPath }}/database.yaml
    text:
      - title: Próximos passos
        content: |
          ## Database PostgreSQL criado com sucesso! 🎉
          
          **Nome do Claim:** `${{ parameters.claimName }}`
          **Nome do Database:** `${{ parameters.databaseName }}`
          **Ambiente:** `${{ parameters.environment }}`
          **Política de Deleção:** `${{ parameters.deletionPolicy }}`
          
          ### Como aplicar:
          
          ```bash
          kubectl apply -f database.yaml
          ```
          
          ### Verificar status:
          
          ```bash
          kubectl get dakipostgresdatabases ${{ parameters.claimName }}
          kubectl describe dakipostgresdatabase ${{ parameters.claimName }}
          ```
          
          ### Ver database no PostgreSQL:
          
          ```bash
          kubectl get databases.postgresql.postgresql.upbound.io
          ```
          
          ### Deletar (quando necessário):
          
          ```bash
          kubectl delete dakipostgresdatabase ${{ parameters.claimName }}
          ```
          
          {% if parameters.deletionPolicy == "Orphan" %}
          ⚠️ **Atenção:** Você escolheu `deletionPolicy: Orphan`. O database permanecerá no PostgreSQL mesmo após deletar o claim.
          {% endif %}
          
          {% if parameters.environment == "production" %}
          🔒 **Produção:** Recomendamos usar `deletionPolicy: Orphan` e `connectionLimit` apropriado.
          {% endif %}
