apiVersion: dakikafkatopic.example.com/v1alpha1
kind: DakiKafkaTopic
metadata:
  name: ${{ values.topicName }}
  namespace: default
spec:
  parameters:
    topicName: ${{ values.topicName }}
    providerConfigRef: confluent-topic-staging
    partitions_count: ${{ values.partitions_count }}
    deletionPolicy: ${{ values.deletionPolicy }}
