apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-database
  title: PostgreSQL Database
spec:
  owner: group:default/daki
  type: service

  parameters:
    - title: Dados do banco
      required:
        - databaseName
      properties:
        databaseName:
          type: string
          title: Nome do banco

  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./skeleton
        values:
          databaseName: ${{ parameters.databaseName }}
