apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-database
  title: PostgreSQL Database (Crossplane)
  description: Provisiona um PostgreSQL via Crossplane
spec:
  owner: teste
  type: resource

  parameters:
    - title: Database configuration
      required:
        - name
      properties:
        name:
          title: Database name
          type: string

  steps:
    - id: fetch
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.fetch.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml
