apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: daki-postgres-database
  title: Daki PostgreSQL Database
  description: Cria um database PostgreSQL usando Crossplane e abre PR no GitHub
  tags:
    - crossplane
    - postgresql
    - database
spec:
  owner: platform-team
  type: template

  parameters:
    - title: Informações do Database
      required:
        - databaseName
        - claimName
      properties:
        databaseName:
          title: Nome do Database
          type: string
          description: Nome do database PostgreSQL (use snake_case)
          pattern: '^[a-z][a-z0-9_]*$'
          ui:autofocus: true
        claimName:
          title: Nome do Claim
          type: string
          description: Nome do recurso Kubernetes (use kebab-case)
          pattern: '^[a-z][a-z0-9-]*$'

    - title: Configurações Avançadas
      properties:
        connectionLimit:
          title: Limite de Conexões
          type: integer
          default: -1
        allowConnections:
          title: Permitir Conexões
          type: boolean
          default: true
        deletionPolicy:
          title: Política de Deleção
          type: string
          default: Delete
          enum:
            - Delete
            - Orphan
        environment:
          title: Ambiente
          type: string
          default: development
          enum:
            - development
            - staging
            - production
        providerConfigRef:
          title: Provider Config
          type: string
          default: poc-postgres-aurora

  steps:
    - id: fetch-base
      name: Preparar template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          databaseName: ${{ parameters.databaseName }}
          claimName: ${{ parameters.claimName }}
          connectionLimit: ${{ parameters.connectionLimit }}
          allowConnections: ${{ parameters.allowConnections }}
          deletionPolicy: ${{ parameters.deletionPolicy }}
          environment: ${{ parameters.environment }}
          providerConfigRef: ${{ parameters.providerConfigRef }}

    - id: log
      name: Log dos arquivos gerados
      action: debug:log
      input:
        message: "Arquivos gerados para ${{ parameters.claimName }}"

    - id: create-pr
      name: Abrir PR no GitHub
      action: github:pull-request
      input:
        repoUrl: https://github.com/spaschoalick/backstage
        sourceBranch: backstage-database-${{ parameters.claimName }}
        title: "Criar banco ${{ parameters.databaseName }}"
        body: "PR gerado automaticamente pelo template Backstage para criar o banco ${{ parameters.databaseName }}"
        commitMessage: "Adicionar banco ${{ parameters.databaseName }}"
        files:
          - path: ${{ steps.fetch-base.output.targetPath }}/database.yaml
        authorName: Backstage Bot
        authorEmail: backstage-bot@example.com

  output:
    links:
      - title: Arquivo YAML gerado
        icon: description
        url: ${{ steps.fetch-base.output.targetPath }}/database.yaml
    text:
      - title: Próximos passos
        content: |
          ## Database PostgreSQL criado com sucesso! 🎉
          
          **Nome do Claim:** `${{ parameters.claimName }}`
          **Nome do Database:** `${{ parameters.databaseName }}`
          **Ambiente:** `${{ parameters.environment }}`
          **Política de Deleção:** `${{ parameters.deletionPolicy }}`
          
          ### Como aplicar localmente:
          ```bash
          kubectl apply -f ${{ steps.fetch-base.output.targetPath }}/database.yaml
          ```
          
          ### Ver status do resource:
          ```bash
          kubectl get dakipostgresdatabases ${{ parameters.claimName }}
          kubectl describe dakipostgresdatabase ${{ parameters.claimName }}
          ```
          
          ### Deletar quando necessário:
          ```bash
          kubectl delete dakipostgresdatabase ${{ parameters.claimName }}
          ```
