apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-daki-postgres
  title: Novo Banco PostgreSQL (Push)
spec:
  owner: guest
  type: service
  parameters:
    - title: Dados
      required: [db_name]
      properties:
        db_name:
          title: Nome do Banco
          type: string
  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./content
        templateFileExtension: true
        values:
          db_name: ${{ parameters.db_name }}

    - id: publish
      action: publish:github:push
      input:
        repoUrl: "github.com?owner=spaschoalick&repo=backstage"
        # Aqui o parâmetro correto é branchName
        branchName: "infra-${{ parameters.db_name }}"
        commitMessage: "feat: adiciona instancia de banco ${{ parameters.db_name }}"
        sourcePath: "." # Sobe tudo o que foi gerado no fetch
        targetPath: "database/instances/${{ parameters.db_name }}"

  output:
    links:
      - title: Ver código no GitHub
        url: "https://github.com/spaschoalick/backstage/tree/infra-${{ parameters.db_name }}"
