apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-daki-postgres
  title: Novo Banco PostgreSQL (Versao Estavel)
  description: Esta versao usa o formato simplificado que sempre funciona.
spec:
  owner: guest
  type: service

  parameters:
    - title: Dados do Banco
      required: [db_name]
      properties:
        db_name:
          title: Nome do Banco
          type: string

  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./content
        # Garantindo que ele processe as chaves {{ }}
        templateFileExtension: true
        values:
          db_name: ${{ parameters.db_name }}

    - id: publish
      action: publish:github:pull-request
      input:
        # Formato de URL mais estável do Backstage
        repoUrl: "github.com?owner=spaschoalick&repo=backstage"
        branchName: main
        # Usando um nome fixo + variavel para garantir que abra
        targetBranchName: "patch-${{ parameters.db_name }}"
        title: "infra: adicionar banco ${{ parameters.db_name }}"
        description: "PR gerado pelo Scaffolder do Backstage"
        targetPath: "database/instances/${{ parameters.db_name }}"

  output:
    links:
      - title: Ver Pull Request no GitHub
        url: ${{ steps['publish'].output.remoteUrl }}
