apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-daki-postgres
  title: Novo Banco PostgreSQL (Simples)
  description: Gera o manifesto com o nome correto
spec:
  owner: guest
  type: service

  parameters:
    - title: Configuracoes Basicas
      required: [db_name]
      properties:
        db_name:
          title: Nome do Banco
          type: string

  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./content
        values:
          db_name: ${{ parameters.db_name }}

    - id: publish
      action: publish:github:pull-request
      input:
        repoUrl: "github.com?owner=spaschoalick&repo=backstage"
        branchName: main
        # Adicionando um número aleatório simples para evitar conflito de branch
        targetBranchName: "infra-db-${{ parameters.db_name }}-v2"
        title: "infra: novo banco ${{ parameters.db_name }}"
        description: "PR gerado automaticamente pelo Backstage"
        targetPath: "database/instances/${{ parameters.db_name }}"

  output:
    links:
      - title: Ver Pull Request no GitHub
        url: ${{ steps['publish'].output.remoteUrl }}
