apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-daki-postgres
  title: Novo Banco PostgreSQL (Versao Blindada)
spec:
  owner: guest
  type: service
  parameters:
    - title: Dados
      required: [db_name]
      properties:
        db_name:
          title: Nome do Banco
          type: string

  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./content
        templateFileExtension: true
        values:
          db_name: ${{ parameters.db_name }}

    - id: publish
      action: publish:github
      input:
        repoUrl: "github.com?owner=spaschoalick&repo=backstage"
        # Isso faz o push direto para uma branch nova sem abrir o PR
        branchName: "infra-${{ parameters.db_name }}"

  output:
    links:
      - title: Ver Pull Request no GitHub
        url: ${{ steps['publish'].output.remoteUrl }}
