apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-daki-postgres
  title: Novo Banco PostgreSQL (Crossplane)
spec:
  owner: guest
  type: service

  parameters:
    - title: Configurações
      required: [db_name]
      properties:
        db_name:
          title: Nome do Banco
          type: string

  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./content
        values:
          db_name: ${{ parameters.db_name }}

    - id: publish
      action: publish:github:pull-request
      input:
        # Mudança: Usando a URL completa do projeto para forçar o reconhecimento
        repoUrl: "github.com?repo=backstage&owner=spaschoalick"
        branchName: main
        targetBranchName: "infra-db-${{ parameters.db_name }}"
        title: "infra: novo banco ${{ parameters.db_name }}"
        description: "PR gerado via Backstage."
        targetPath: "database/instances/${{ parameters.db_name }}"

  output:
    links:
      - title: Ver Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
